Certificate Verification
hass-api/hassapi pull request #4
Opened 2023-03-09 10:19 UTC by N4S4

Good day,

thanks for the repo 
there might be the case, like mine where my Hass instance has a certificate and when making local requests wont be approved as is insecure.

The following PR adds an optional argument to the api where you could bypass verification. 
This would help my code to be updated with main branch

thank you

2023-03-09 14:12 UTC, N4S4 commented
also added the ability to set attributes from [hassapi-extended](https://github.com/Kuwertzel/hassapi-extended)

2023-09-18 09:13 UTC, vadimtitov requested changes
Hey @N4S4
Sorry, wasn't looking at this for a while
Thanks for contributing, I've left a few comments

2023-09-18 09:13 UTC, vadimtitov commented on src/hassapi/client/base.py
> +
I'd remove this since I don't think all warning should be just completely disabled
```suggestion
```

2023-09-18 09:13 UTC, vadimtitov commented on src/hassapi/client/base.py
> +        self, hassurl: Optional[str] = None, token: Optional[str] = None, verify: Optional[bool] = None, timeout: float = 3
booleans don't need to be optional since there are just 2 values
```suggestion
        self, hassurl: Optional[str] = None, token: Optional[str] = None, verify: bool = True, timeout: float = 3
```

2023-09-18 09:13 UTC, vadimtitov commented on src/hassapi/client/states.py
> +    def set_state(self, entity_id: str, state: HassValueType, attributes: dict = None) -> State:
```suggestion
    def set_state(self, entity_id: str, state: HassValueType, attributes: Optional[Dict[str, HassValueType]]  = None) -> State:
```
?

2023-09-18 18:08 UTC, merged

2023-09-18 20:00 UTC, N4S4 commented
Hi sorry i did not answer in time, yeah you are right with the changes, thank you for merging

2023-09-18 21:13 UTC, vadimtitov commented
> Hi sorry i did not answer in time, yeah you are right with the changes, thank you for merging

Thanks 👍  released as `0.2.0`